services:
  nexus:
    image: sonatype/nexus3:3.87.1
    container_name: nexus
    restart: no
    ports:
      - "${CINEMA__NEXUS__PORT}:8081"
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:
